"""Vault access: seeding, notes, projects, activity, hot.md, checks, log."""
from __future__ import annotations

import os
import shutil
import subprocess
from datetime import date
from pathlib import Path

from frontmatter import FrontmatterError, open_items, parse, wikilinks

RESERVED = {"hot.md", "log.md", "types.md"}
_SKIP_DIRS = {"templates"}


def seed(vault: Path, seed_dir: Path) -> list:
    copied = []
    for src in sorted(Path(seed_dir).rglob("*")):
        if src.is_dir():
            continue
        dst = vault / src.relative_to(seed_dir)
        if not dst.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)
            copied.append(dst)
    return copied


def _is_note(vault: Path, path: Path) -> bool:
    rel = path.relative_to(vault)
    if any(part.startswith(".") for part in rel.parts) or rel.parts[0] in _SKIP_DIRS:
        return False
    return not (len(rel.parts) == 1 and rel.name in RESERVED)


def _notes(vault: Path) -> list:
    return sorted(p for p in vault.rglob("*.md") if _is_note(vault, p))


def iter_notes(vault: Path, errors: list = None):
    for path in _notes(vault):
        try:
            meta, body = parse(path.read_text(encoding="utf-8"))
        except (FrontmatterError, OSError, UnicodeDecodeError) as e:
            if errors is not None:
                errors.append((path, str(e)))
            continue
        yield path, meta, body


def project_root(cwd: str) -> Path:
    here = Path(cwd).expanduser()
    try:
        out = subprocess.run(["git", "-C", str(here), "rev-parse", "--path-format=absolute", "--git-common-dir"],
                             capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.TimeoutExpired):
        return here.resolve()
    if out.returncode != 0 or not out.stdout.strip():
        return here.resolve()
    common = Path(out.stdout.strip())
    return (common.parent if common.name == ".git" else common).resolve()


def find_project_note(vault: Path, root: Path):
    for path, meta, _ in iter_notes(vault):
        if meta.get("type") == "project" and meta.get("path"):
            if Path(str(meta["path"])).expanduser().resolve() == Path(root).resolve():
                return path
    return None


def project_name(vault: Path, cwd: str) -> tuple:
    root = project_root(cwd)
    note = find_project_note(vault, root) if vault else None
    return (note.stem if note else root.name), root


def find_session_note(vault: Path, session_id: str):
    sessions = vault / "sessions"
    if not sessions.is_dir():
        return None
    for path in sorted(sessions.rglob("*.md")):
        try:
            meta, _ = parse(path.read_text(encoding="utf-8"))
        except (FrontmatterError, OSError, UnicodeDecodeError):
            continue
        if meta.get("session_id") == session_id:
            return path
    return None


def is_active(meta: dict, today: date, days: int) -> bool:
    if meta.get("pinned") is True:
        return True
    if meta.get("status") == "closed":
        return False
    try:
        last = date.fromisoformat(str(meta.get("last_active", ""))[:10])
    except ValueError:
        return False
    return (today - last).days <= days


def active_notes(vault: Path, today: date, days: int) -> list:
    notes = [n for n in iter_notes(vault) if n[1].get("type") != "session" and is_active(n[1], today, days)]
    notes.sort(key=lambda n: str(n[1].get("last_active", "")), reverse=True)
    notes.sort(key=lambda n: n[1].get("pinned") is not True)
    return notes


def hot_line(path: Path, meta: dict, body: str) -> str:
    n = len(open_items(body))
    line = f"- [[{path.stem}]] ({meta.get('type', '?')}, {meta.get('last_active', '?')}): {meta.get('summary', '')}"
    return line + (f" · {n} open" if n else "")


def build_hot(vault: Path, today: date, days: int) -> Path:
    lines = [hot_line(*n) for n in active_notes(vault, today, days)]
    text = ("# Hot\n\nActive notes, generated by dory. Do not edit; changes are overwritten.\n\n"
            + "\n".join(lines) + "\n")
    path = vault / "hot.md"
    path.write_text(text, encoding="utf-8")
    return path


def snapshot(vault: Path) -> set:
    out = set()
    for p in vault.rglob("*"):
        rel = p.relative_to(vault)
        if any(part.startswith(".") for part in rel.parts):
            continue
        out.add(rel.as_posix() + ("/" if p.is_dir() else ""))
    return out


def changed_since(vault: Path, since: float) -> list:
    return [p for p in _notes(vault) if p.stat().st_mtime >= since]


def dead_links(vault: Path, files: list) -> list:
    names = {p.stem.lower() for p in vault.rglob("*.md")}
    dead = []
    for f in files:
        for target in wikilinks(f.read_text(encoding="utf-8")):
            name = target.split("/")[-1]
            suffix = Path(name).suffix.lower()
            if suffix and suffix != ".md":
                continue  # ponytail: attachments are not checked
            stem = Path(name).stem.lower() if suffix else name.lower()
            if stem not in names:
                dead.append((f, target))
    return dead


def conflict_files(vault: Path) -> list:
    return sorted(p for p in vault.rglob("*conflicted copy*") if p.is_file())


def append_log(vault: Path, line: str) -> None:
    with open(vault / "log.md", "a", encoding="utf-8") as f:
        f.write(line.rstrip("\n") + "\n")


def writable(vault) -> bool:
    return bool(vault) and Path(vault).is_dir() and os.access(vault, os.W_OK)
